# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Learn"
license = "MIT"
licenselink = "https://github.com/LaunchCodeTechnicalTraining/hugo-theme-learn/blob/master/LICENSE.md"
description = "Documentation theme for LaunchCode curriculum development adpated from Learn by Mathieu Cornic."
homepage = "https://launchcode.org"
repo = "https://github.com/LaunchCodeTechnicalTraining/hugo-theme-learn"
tags = ["documentation", "grav", "learn", "doc", "search"]
features = ["documentation", "menu", "nested sections", "search", "mermaid"]
min_version = 0.25

[author]
  name = "Paul Matthews"
  homepage = "https://launchcode.org"

[original]
  name = "Mathieu Cornic"
  homepage = "https://matcornic.github.io/"
  repo = "https://github.com/getgrav/grav-learn"
